import Link from "next/link"
import Footer from "../components/Footer"
import NavLink from "../components/NavLink"
import Header from "../components/Header"

import "../components/globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body> 
        <div className="bg-green-100 dark:bg-[#112211] dark:text-white min-h-[100dvh] grid grid-rows-[auto_1fr_auto]">
          <Header />
          <main className="py-4 px-4 m-5">{children}</main>
          <Footer />
        </div>
        
      </body>
    </html>
  )
}
