import Link from "next/link"
import Footer from "../components/Footer"

import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-200 min-h-[100dvh] grid grid-rows-[auto_1fr_auto]">
          <header>
            <Link href="/">Home</Link> | <Link href="/about-us">About Us</Link>
          </header>
          <main>{children}</main>
          <Footer />
        </div>
        
      </body>
    </html>
  )
}
